# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_iso8601_wrappers", use_symbols = TRUE, package_name = "iso8601")

#' @usage NULL
#' @useDynLib iso8601, .registration = TRUE
NULL

#' Funcion para obtener el mes para un determinado isoweek
#'
#' @param years año actual
#' @param weeks semana iso a consultar
#'
#' @return isoweek
#' @export
get_iso_month <- function(years, weeks) .Call(wrap__get_iso_month, years, weeks)


# nolint end
